### ISSUE TITLE
Add support for linux 

### ISSUE THREAD

**Issue by tamvodopad** [netbeast/passbot#1]
Right now if run npm install

```
npm WARN optional Skipping failed optional dependency /babel/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```

**Comment by jsdario** [comment]
Hi @tamvodopad, **npm** should find the appropriate version of babel for you.
Does it completely break the build or it only remains as a `WARN`? Because then it must work.

However, to add Linux support, please tell me if you can do the following:
1. Remove dependencies `rm -rf node_modules`
2. `npm install -g babel-cli`
3. `npm install babel botkit commander fs-promise` as available in **package.json**.
4. `babel-node index.es`

If it works, I'll improve the docs.
If it doesn't I will create some tests, put it on `travis-ci` and maybe fallback to Javascript pre ES6.

In the meantime you can just visit my tonicdev book where you can run the bot and play with it!
https://tonicdev.com/jsdario/passbot

**Comment by tamvodopad** [comment]
Thank you. This work for me on Ubuntu 14.04. Please improve the docs.

**Comment by jsdario** [comment]
Just added support for Linux falling back to ES5, so the docs can remain as they are and less people have trouble having to install dev dependencies. Thanks for your issue!
